name: Fetch API and Commit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"   # Run daily at 01:00 UTC

permissions:
  contents: write   # allow pushing commits
  actions: read

jobs:
  fetch_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # full history for accurate diffs

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Fetch data and generate JSON
        run: node fetch.js

      - name: Detect changes in members.json
        id: detect
        run: |
          if git diff --quiet HEAD -- members.json; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Extract changed indices
        if: steps.detect.outputs.changed == 'true'
        id: diff
        run: |
          git config --local diff.gron.textconv gron
          diff=$(git diff --no-color members.json | grep '^\+' | cut -c2-)
          updated_keys=$(echo "$diff" | awk -F '[][]' '{print $2, $3}' | sort -n)
          update_profile=$(echo "$updated_keys" | grep -oE '^[0-9]+' | sort -nu | tr '\n' '|')
          sns_update=$(echo "$updated_keys" | awk '{sub(/^\./, "", $2); a[$2]=a[$2]" "$1} END {for (k in a) print k a[k]}' | tr '\n' '|')
          echo "update_profile=$update_profile" >> "$GITHUB_OUTPUT"
          echo "sns_update=$sns_update" >> "$GITHUB_OUTPUT"

      - name: Update Profile
        if: steps.detect.outputs.changed == 'true'
        env:
          UPDATE_PROFILE_URL: ${{ secrets.UPDATE_PROFILE_URL }}
          UPDATE_PROFILE_KEY: ${{ secrets.UPDATE_PROFILE_KEY }}
        run: |
          echo "Updating profile indices: ${{ steps.diff.outputs.update_profile }}"
          node update.js update_profile "${{ steps.diff.outputs.update_profile }}"

      - name: Commit and push changes
        if: steps.detect.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add members.json
          git commit -m "chore: update members.json"
          git push

      - name: Update SNS
        if: steps.detect.outputs.changed == 'true'
        env:
          UPDATE_SNS_URL: ${{ secrets.UPDATE_SNS_URL }}
          UPDATE_SNS_KEY: ${{ secrets.UPDATE_SNS_KEY }}
        run: |
          echo "Updating SNS: ${{ steps.diff.outputs.sns_update }}"
          node update.js sns_update "${{ steps.diff.outputs.sns_update }}"
