name: Update User-Agent Gist

on:
  schedule:
    - cron: '0 0 1,16 * *'
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch and filter User-Agents
        run: python update_ua.py

      - name: Update Gist
        env:
          GIST_ID: db31e8b51186a914e0a88db3193aedb9
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          content=$(cat user_agents.txt)
          payload=$(jq -n --arg c "$content" '{"files": {"user_agents.txt": {"content": $c}}}')
          curl -X PATCH \
            -H "Authorization: token $GIST_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$payload" \
            https://api.github.com/gists/$GIST_ID
